name: deploy development

on:
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:
    uses:  ./.github/workflows/unit-tests.yml
  
  deploy_development:
    runs-on: ubuntu-latest
    needs: [unit_tests]
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v2

      - name: Instal deploy dependencies
        run: pip install ziglang cargo-lambda
      
      - name: 📦 Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-lambda-${{ hashFiles('**/Cargo.lock') }}

      - name: 🔨 Build lambda
        run: make lambda-build
      
      - name: 🚀 Deploy development
        run: make lambda-deploy-development

